USE BLOG_PROJECT;

SELECT * FROM USUARIOS;
SELECT * FROM CATEGORIAS;
SELECT * FROM ENTRADAS;

SELECT E.ID, E.USUARIO_ID, U.NOMBRE AS USUARIO, U.EMAIL AS USUARIO_EMAIL, E.CATEGORIA_ID, C.NOMBRE AS CATEGORY, E.TITULO, E.DESCRIPTION, E.FECHA FROM ENTRADAS E LEFT OUTER JOIN USUARIOS U ON E.USUARIO_ID=U.ID LEFT OUTER JOIN CATEGORIAS C ON E.CATEGORIA_ID=C.ID ORDER BY ID ASC WHERE E.CATEGORIA_ID=1