
/*CREATE DATABASE BLOG_PROJECT;

CREATE USER 'Blog'@'localhost' IDENTIFIED BY 'Blog@1234';
GRANT ALL PRIVILEGES ON BLOG_PROJECT.* TO 'Blog'@'localhost';
*/
USE BLOG_PROJECT;

CREATE TABLE USUARIOS(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
    CONSTRAINT UQ_USUARIOS_EMAIL UNIQUE(EMAIL)
) ENGINE=InnoDb;

INSERT INTO USUARIOS VALUES (1, 'unknown', 'unknown', 'unknown@BlogJose.com', '7381be761d67037a436fc4a03c96f067', '2021-12-06');

CREATE TABLE CATEGORIAS(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100),
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY(ID)
) ENGINE=InnoDb;

INSERT INTO CATEGORIAS VALUES (0, 'unknown');

CREATE TABLE ENTRADAS(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    USUARIO_ID INT(255) NOT NULL,
    CATEGORIAS_ID INT(255) NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DESCRIPTION MEDIUMTEXT,
    FECHA DATE NOT NULL,
    CONSTRAINT PK_ENTRADAS PRIMARY KEY(ID),
    CONSTRAINT FK_ENTRADAS_USUARIOS FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_ENTRADAS_CATEGORIAS FOREIGN KEY(CATEGORIAS_ID) REFERENCES CATEGORIAS(ID) ON DELETE NO ACTION
) ENGINE=InnoDb;